### ISSUE TITLE
Swiping one parallax swipes another parallax

### ISSUE THREAD

**Issue by mrishan1993** [zachgibson/react-native-parallax-swiper#24] opened 2018-04-16 19:37 UTC
I created a flatlist which renders a parallax in each row.
The problem is when I swipe one parallax, another parallax swipes as well.
This is how I am rendering my parallaxes
`render () {
    return (
      <View style={styles.navBar}>
        <ParallaxSwiper
         speed={0.5}
         dividerWidth={0}
         dividerColor="white"
         backgroundColor="white"
         progressBarBackgroundColor="rgba(0,0,0,0.25)"
         progressBarValueBackgroundColor="white"
         >
         {this.props.item.frame.map(function(image, i){
                      return (
                        <ParallaxSwiperPage
                          BackgroundComponent={
                            <Image
                              style={styles.backgroundImage}
                              source={{ uri: image.url }}
                            />
                          }
                        />
                      )
                  },this)}
       </ParallaxSwiper>
      </View>
    )
  }`

Each frame has some image urls

These are the styles I am using
`navBar: {
  display: 'flex',
  flex: 1,
  backgroundColor: '#f1f1f1',
  height: 400,
  },
  backgroundImage: {
    width: width,
    height: 400
  },`

Please suggest.

**Comment by zachgibson** [comment] 2018-04-26 20:50
If you can, please create an [expo snack](https://snack.expo.io/) with your code so I can see what’s going on.

**Comment by zachgibson** [comment] 2018-06-03 22:41
@mrishan1993 Since I can’t reproduce, I can’t help. Closing this.

**Closed as completed by zachgibson** 2018-06-03 22:41 UTC
Labels: question
